- name: Install applications for Ubuntu
  tags:
    - pkg
  block:
    - name: Setup Structure
      ansible.builtin.include_tasks: structure.yml
    - name: Setup SSH Access
      ansible.builtin.include_tasks: access.yml
    - name: Setup MOTD
      ansible.builtin.include_tasks: motd.yml
