- name: Sets up machine
  block:
    - name: Check tailscale installed
      ansible.builtin.stat:
        path: /usr/bin/tailscaled
      register: tailscale_check
    - name: 'Pihole running'
      ansible.builtin.systemd:
        name: pihole-FTL.service
        state: started
        enabled: true
      when: pihole_enabled # Comes from host variables
    - name: 'Tailscaled running'
      ansible.builtin.systemd:
        name: tailscaled
        state: started
        enabled: true
      when: tailscale_check.stat.exists
